# Generated by Django 4.2.19 on 2025-04-06 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0004_alter_user_temp_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(max_length=255)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_entries', to='userauth.child')),
            ],
        ),
    ]
