# Generated by Django 4.2.19 on 2025-04-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_conditiontype_alter_equipmentitem_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='marketplace.conditiontype'),
        ),
    ]
