# Generated by Django 4.2.19 on 2025-04-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_comment_parent_discussionpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionpost',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='discussionpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='forum.discussioncategory'),
        ),
    ]
