# Generated by Django 4.2.19 on 2025-05-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_options_remove_comment_parent_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='parent',
        ),
    ]
