# Generated by Django 4.2.19 on 2025-06-22 19:43

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='donation_photo')),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='donations.donationrequest')),
            ],
        ),
    ]
