# Generated by Django 4.2.19 on 2025-06-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='photo',
        ),
    ]
