# Generated by Django 4.2.19 on 2025-03-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_infocategory_infocomment_infopost_infotag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopost',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
