# Generated by Django 4.2.19 on 2025-04-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0004_infopost_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopost',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='infocomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_info_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='information.infocomment'),
        ),
    ]
