# Generated by Django 4.2.19 on 2025-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_delete_infocategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
