# Generated by Django 4.2.19 on 2025-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
