# Generated by Django 4.2.19 on 2025-04-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_specialist_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
