# Generated by Django 4.2.19 on 2025-05-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_therapycenterreply_specialistreply_newsreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='newsreply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='specialistcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='specialistreply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='therapycentercomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='therapycenterreply',
            name='likes',
        ),
    ]
