# Generated by Django 4.2.19 on 2025-05-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_remove_newscomment_likes_remove_newsreply_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='specialistcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='therapycentercomment',
            name='parent',
        ),
    ]
