# Generated by Django 4.2.19 on 2025-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
