# Generated by Django 4.2.19 on 2025-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dy936wtgc/image/upload/v1742898556/balasteps/ekcozvxutn136qtdorad.jpg', null=True),
        ),
    ]
