# Generated by Django 4.2.19 on 2025-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
